# This compose file is intended for use in a development environment.
# It includes test suites and bind mounts so containers will use latest code updates.

services:
  config-app:
    build:
      context: .
      dockerfile: "./config_portal/Dockerfile-dev-config"
    ports:
      - "8040:8040"
    expose:
      - "8040"
    volumes:
      - type: bind
        source: ./config_portal
        target: /app
      - type: bind
        source: ./components
        target: /app/components
      - type: bind
        source: ./styles
        target: /app/assets/styles
      - config-data-dev:/config
  display-app:
    build: 
      context: .
      dockerfile: "./app/Dockerfile-dev-dash"
    ports:
      - "8050:8050"
    expose:
      - "8050"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./components
        target: /app/components
      - type: bind
        source: ./styles
        target: /app/assets/styles
      - config-data-dev:/app/assets/config
volumes:
  config-data-dev:
    external: true
