# This compose file is intended for use in a development environment.
# It includes test suites and bind mounts so containers will use latest code updates.

services:
  config-app:
    build:
      context: .
      dockerfile: "./Dockerfile-all"
      target: dev-config
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    ports:
      - "8040:8040"
    expose:
      - "8040"
    volumes:
      - type: bind
        source: ./config_portal
        target: /home/nonroot/app
      - type: bind
        source: ./components
        target: /home/nonroot/app/components
      - type: bind
        source: ./styles
        target: /home/nonroot/app/assets/styles
      - config-data-dev:/config
  display-app:
    build: 
      context: .
      dockerfile: "./Dockerfile-all"
      target: dev-display
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    ports:
      - "8050:8050"
    expose:
      - "8050"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./app
        target: /home/nonroot/app
      - type: bind
        source: ./components
        target: /home/nonroot/app/components
      - type: bind
        source: ./styles
        target: /home/nonroot/app/assets/styles
      - config-data-dev:/home/nonroot/app/assets/config
volumes:
  config-data-dev:
    external: true
