# This compose file prepares a production image of the software, which can then
# be published to Docker Hub and run on production using docker-compose-prod.yaml.

services:
  display:
    build:
      context: .
      dockerfile: "./Dockerfile-all"
      target: prod-display
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
      platforms: 
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8050:8050"
    stdin_open: true
    tty: true
    restart: on-failure:5
    volumes:
      - config-data:/home/nonroot/app/assets/config
  config:
    build:
      context: .
      dockerfile: "./Dockerfile-all"
      target: prod-config
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
      platforms: 
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8040:8040"
    stdin_open: true
    tty: true
    restart: on-failure:5
    volumes:
      - config-data:/config
volumes:
  config-data:
    external: true
