services:

  display:
    build:
      context: .
      dockerfile: "./app/Dockerfile"
      platforms: 
        - "linux/amd64"
    ports:
      - "8050:8050"
    stdin_open: true
    tty: true
    restart: on-failure:5
    volumes:
      - config-data:/app/assets/config
  config:
    build:
      context: .
      dockerfile: "./config_portal/Dockerfile-config"
      platforms: 
        - "linux/amd64"
    ports:
      - "8040:8040"
    stdin_open: true
    tty: true
    restart: on-failure:5
    volumes:
      - config-data:/config
volumes:
  config-data:
    external: true
#     networks:
#       - inside
# networks:
#   inside:
#     internal: true
#   outside:
