services:
  display:
    extends:
      file: docker-compose-dev.yaml
      service: display-app
    volumes:
    - config-data-test:/app/assets/config
  config:
    extends:
      file: docker-compose-dev.yaml
      service: config-app
    volumes:
    - config-data-test:/config
volumes:
  config-data-test:
    external: true