# This compose file prepares a development image of the software using bind mounts.

name: tde-dev
services:
  display:
    extends:
      file: docker-compose.yaml
      service: display
    volumes:
      - type: bind
        source: ./app
        target: /home/nonroot/app
      - type: bind
        source: ./components
        target: /home/nonroot/app/components
      - type: bind
        source: ./styles
        target: /home/nonroot/app/assets/styles
      - config-data-dev:/home/nonroot/app/assets/config
  config:
    extends:
      file: docker-compose.yaml
      service: config
    volumes:
      - type: bind
        source: ./config_portal
        target: /home/nonroot/app
      - type: bind
        source: ./components
        target: /home/nonroot/app/components
      - type: bind
        source: ./styles
        target: /home/nonroot/app/assets/styles
      - config-data-dev:/config
volumes:
  config-data-dev:
    external: true
    name: ${VOLUME:-config-data-dev}