FROM python:3.13-bookworm AS poetry
RUN pip install "poetry==1.8.4"
WORKDIR /app
COPY ./pyproject.toml ./poetry.lock ./
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes --with=config

FROM python:3.13-bookworm
RUN apt-get update && apt-get install python3 ffmpeg libsm6 libxext6  -y
WORKDIR /app
COPY --from=poetry /app/requirements.txt .
RUN pip install -r ./requirements.txt
COPY ./config_portal/app.py \
     ./config_portal/gunicorn_conf.py \
     ./
COPY ./config_portal/assets \
     ./assets
COPY ./config_portal/config_components \
     ./config_components
COPY ./config_portal/pages \
     ./pages
COPY ./components \
     ./components
COPY ./config_portal/examples \
     ./examples
COPY ./styles \
     ./assets/styles

RUN chmod +rx ./app.py

ENV PATH="/app:$PATH"
ENV PORT=8040
EXPOSE 8040
ENTRYPOINT ["gunicorn", "-c", "gunicorn_conf.py", "app:server"]
